.TH FFTOP "1" "JANUARY 2019" "fftop 0.5" "User Commands"
.SH NAME
fftop \- Bouncy Power Spectrum!
.SH SYNOPSIS
.B fftop
.SH DESCRIPTION
Displays a live power spectral density chart from the sound from the default microphone.
.SH Notes
Tested on Debian 9.6, OSX 10.13.6, FreeBSD 12, Raspbian 9.5 and Windows using MingW64
InitScripts only tested on Linux.
.SH "REPORTING BUGS"
Report bugs to: bugs@wbh.org
.br
FFTop home page: <http://wbh.org/code>
.SH COPYRIGHT
Copyright \(co 2019 W.B.Hill <mail@wbh.org>
.br
License, dual. Either GPLv2 or BSD 2 clause, as appropriate.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
